Mode: 1
ProtoFolder: "../cmd/pb"
FromDatabase:
  Host: "192.168.0.41"
  Port: 3306
  DbName: "pekomiko"
  User: "db_user"
  Password: "password"
FromTable: "Account"
ToDatabase:
  Host: "192.168.0.41"
  Port: 3306
  DbName: "pekomiko"
  User: "db_user"
  Password: "password"
ToTable: "Account"
Generate: true
Print: false
Sync: true